#!python

"""
        COPYRIGHT (c) 2022 by Featuremine Corporation.
        This software has been provided pursuant to a License Agreement
        containing restrictions on its use.  This software contains
        valuable trade secrets and proprietary information of
        Featuremine Corporation and is protected by law.  It may not be
        copied or distributed in any form or medium, disclosed to third
        parties, reverse engineered or used in any manner not provided
        for in said License Agreement except with the prior written
        authorization from Featuremine Corporation.
"""

import unittest
import importlib
import sys


tests_module = "@TESTS_PACKAGE@"

if __name__ == '__main__':
    mod = importlib.import_module(tests_module if len(sys.argv) <= 1 else f"{tests_module}.{sys.argv[1]}")
    dir = mod.__path__[0]
    testsuite = unittest.defaultTestLoader.discover(start_dir=dir, pattern='*.py')
    assert unittest.TextTestRunner(verbosity=2,failfast=True).run(testsuite).wasSuccessful(), 'Test runner failed'
