name: CMake PR

on:
  pull_request:

permissions: write-all

jobs:
  # utility:
  #   runs-on: ubuntu-20.04
  #   outputs:
  #     release-check: ${{ steps.release-check.outputs.release-check }}
    
  #   steps:
  #   - name: Utility tasks
  #     id: release-check
  #     uses: featuremine/actions/utility@main
  #     with:
  #       gh_token: ${{ secrets.GITHUB_TOKEN }}
  #       utility_token: ${{ secrets.UTILITY_COMMIT_TOKEN }}
  #       mypy: true

  # build-manylinux:
  #   #needs: utility
  #   runs-on: ubuntu-20.04
  #   container:
  #     image: public.ecr.aws/p0w8t0l8/ci-hosted-gh-centos7-gcc10.2.0
    
  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       submodules: recursive

  #   - name: Install numdiff
  #     working-directory: /tmp
  #     run: |
  #       wget http://mirror.cedia.org.ec/nongnu/numdiff/numdiff-5.9.0.tar.gz
  #       tar -xvzf numdiff-5.9.0.tar.gz
  #       cd numdiff-5.9.0
  #       ./configure
  #       make
  #       make install
  #       cd ..
  #       rm -rf numdiff-5.9.0*
  #     shell: bash

  #   - name: Build ${{ github.event.repository.name }} with fm gcc
  #     uses: featuremine/actions/package/build@main
  #     with:
  #       gh_token: ${{ secrets.GITHUB_TOKEN }}
  #       yamal_version: '7.2.23'
  #       cpack: TGZ
  #       upload: true
  #       #TODO: Add test_pypi_token when extractor name is available
  #       #test_pypi_token: ${{ secrets.TEST_PYPI_API_TOKEN }}

  # build-macos:
  #   #needs: utility
  #   runs-on: macos-11

  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       submodules: recursive

  #   - name: Install dependencies
  #     run: brew install pkg-config cmake googletest python

  #   - name: Install numdiff
  #     working-directory: /tmp
  #     run: |
  #       wget http://mirror.cedia.org.ec/nongnu/numdiff/numdiff-5.9.0.tar.gz
  #       tar -xvzf numdiff-5.9.0.tar.gz
  #       cd numdiff-5.9.0
  #       ./configure
  #       make
  #       make install
  #       cd ..
  #       rm -rf numdiff-5.9.0*
  #     shell: bash

  #   - name: Build ${{ github.event.repository.name }} with fm gcc
  #     uses: featuremine/actions/package/build@test-macos
  #     with:
  #       gh_token: ${{ secrets.GITHUB_TOKEN }}
  #       yamal_version: '7.2.23'
  #       cpack: TGZ
  #       upload: true

  test-centos:
    #needs: [utility, build-manylinux]
    #if: needs.utility.outputs.release-check == 'release'
    runs-on: ubuntu-20.04
    container:
      image: public.ecr.aws/p0w8t0l8/ci-hosted-gh-centos7-gcc10.2.0
    
    steps:
    - name: Test ${{ github.event.repository.name }} release
      uses: featuremine/actions/package/test@test-macos
      with:
        gh_token: ${{ secrets.GITHUB_TOKEN }}
        yamal_version: '7.2.23'

  test-pythons:
    #needs: [utility, build-manylinux]
    #if: needs.utility.outputs.release-check == 'release'
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12]
        python_version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
        exclude:
          - os: macos-12
            python_version: '3.6'
          - os: macos-12
            python_version: '3.7'
          - os: macos-12
            python_version: '3.8'
          #- os: macos-12
          #  python_version: '3.9'
          - os: macos-12
            python_version: '3.10'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - uses: patch
        run: pip3 install --upgrade setuptools pip

      - name: Test ${{ github.event.repository.name }} release for python version ${{ matrix.python_version }}
        uses: featuremine/actions/package/test@test-macos
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          yamal_version: '7.2.23'
          sudo: true
